### PR TITLE
[WIP] Implement all the things

### PR DESCRIPTION
**Pull request by TylorS**
This is a work in progress to close issue #1

### CODE REVIEW

**Comment by ghost** [comment]
:+1: for this. I think this will be a viable alternative to xstream, combining the best of most and it.

**Comment by TylorS** [comment]
@eshansingh I'm not really ready to share yet, so please keep this a bit quiet :)

**Comment by ghost** [comment]
Ok, I understand.

**Comment by TylorS** [comment]
LGTM

**Pull request merged**
